name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Prepare Git History
        run: git fetch --unshallow

      - name: Commit and Push Snake SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg || echo "No changes to commit"
          git commit -m "Update Snake Game SVG" || echo "No changes to commit"
          git push
