name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark

      - name: Prepare Git History
        run: git fetch --unshallow

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Pull latest changes before pushing
        run: |
          git pull origin main || echo "Failed to pull latest changes. Continuing..."

      - name: Commit generated files
        run: |
          git add dist/github-snake.svg || echo "No changes to commit"
          git add dist/github-snake-dark.svg || echo "No changes to commit"
          git commit -m "Update Snake Game SVG" || echo "No changes to commit"

      - name: Pull latest changes before pushing
        run: |
          git pull origin main || echo "Failed to pull latest changes. Continuing..."

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
